name: .NET

on:
  push:

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet publish --no-restore --configuration Release --output .\out
    - name: Hash
      run: Get-FileHash .\out\pipecat.exe | Format-List
    - name: Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: pipecat
        path: .\out\pipecat.exe
